import { mkdirSync, renameSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { MemoryLogEntry, MemorySnapshot } from "../storage/sqlite.js";

export const AUTO_GENERATED_HEADER = "<!-- AUTO-GENERATED by Agoryx. DO NOT EDIT. -->";
export const MEMORY_FILE_RELATIVE_PATH = join(".agoryx", "memory.md");

interface RenderMetadata {
  generatedAt?: string;
  roomId?: string;
}

const stringifyPayload = (payload: unknown): string => {
  const encoded = JSON.stringify(payload);
  if (!encoded) {
    return "(empty)";
  }
  return encoded.replace(/\|/g, "\\|").replace(/\s+/g, " ").slice(0, 180);
};

const formatWorktree = (value: unknown): string => {
  if (!value || typeof value !== "object") {
    return String(value);
  }

  const record = value as Record<string, unknown>;
  const agent = typeof record.agent === "string" ? record.agent : "";
  const path = typeof record.path === "string" ? record.path : "";
  const branch = typeof record.branch === "string" ? record.branch : "";
  if (!agent && !path && !branch) {
    return JSON.stringify(value);
  }
  const suffix = branch ? ` (${branch})` : "";
  return `${agent || "unknown"} -> ${path || "(unknown path)"}${suffix}`;
};

const renderList = (items: string[]): string[] =>
  items.length > 0 ? items.map((item) => `- ${item}`) : ["- (none)"];

export const renderMemoryMarkdown = (
  snapshot: MemorySnapshot | null,
  recentLog: MemoryLogEntry[],
  metadata: RenderMetadata = {},
): string => {
  const generatedAt = metadata.generatedAt ?? new Date().toISOString();
  const roomId = metadata.roomId ?? snapshot?.roomId ?? recentLog[0]?.roomId ?? "(unknown)";
  const recent = recentLog.slice(-10);
  const worktrees = snapshot?.activeWorktrees ?? [];
  const worktreeText =
    worktrees.length > 0 ? worktrees.map((item) => formatWorktree(item)).join("; ") : "(none)";

  return [
    AUTO_GENERATED_HEADER,
    "# Agoryx Project Memory",
    `Generated: ${generatedAt} | Room: ${roomId}`,
    "",
    "## Current State",
    `- **Goal:** ${snapshot?.currentGoal || "(empty)"}`,
    `- **Branch:** ${snapshot?.activeBranch || "(empty)"}`,
    `- **Worktrees:** ${worktreeText}`,
    `- **Last log id:** ${snapshot?.lastLogId ?? 0}`,
    "",
    "## Key Decisions",
    ...renderList(snapshot?.keyDecisions ?? []),
    "",
    "## Blockers",
    ...renderList(snapshot?.blockers ?? []),
    "",
    "## Next Actions",
    ...renderList(snapshot?.nextActions ?? []),
    "",
    "## Recent Log (last 10)",
    "| Time | Source | Event | Summary |",
    "|------|--------|-------|---------|",
    ...(recent.length > 0
      ? recent.map(
          (event) =>
            `| ${event.timestamp} | ${event.source} | ${event.eventType} | ${stringifyPayload(event.payload)} |`,
        )
      : ["| - | - | - | (none) |"]),
  ].join("\n");
};

export const resolveMemoryFilePath = (rootDir: string): string =>
  join(rootDir, MEMORY_FILE_RELATIVE_PATH);

export const writeMemoryFile = (rootDir: string, content: string): string => {
  const targetPath = resolveMemoryFilePath(rootDir);
  const targetDir = dirname(targetPath);
  mkdirSync(targetDir, { recursive: true });

  const tmpPath = `${targetPath}.tmp-${process.pid}-${Date.now()}`;
  try {
    writeFileSync(tmpPath, content, "utf8");
    renameSync(tmpPath, targetPath);
  } catch (error: unknown) {
    try {
      unlinkSync(tmpPath);
    } catch {
      // best-effort cleanup
    }
    throw error;
  }
  return targetPath;
};
