import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { appendFileSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { claudeProjectKey, isAgoryxPrompt, locateNativeSession, scanNativeSession } from "../../internal/agora/native.js";
import { agentCliScript } from "../../internal/agora/workspace.js";
import { createTestRoom, withTimeout, type TestRoom } from "./helpers.js";

const jsonl = (lines: unknown[]) => lines.map((line) => `${JSON.stringify(line)}\n`).join("");

const scratch = () => mkdtempSync(join(tmpdir(), "agora-native-"));

// --- Claude Code session lines -------------------------------------------------

let n = 0;
const ts = () => new Date(Date.UTC(2026, 8, 28, 10, 0, n++)).toISOString();
const cUser = (content: unknown, extra: Record<string, unknown> = {}) => ({
  type: "user",
  isSidechain: false,
  uuid: `u${n}`,
  promptId: `p${n}`,
  timestamp: ts(),
  message: { role: "user", content },
  ...extra,
});
const cAssistant = (content: unknown[], stop: string | null, extra: Record<string, unknown> = {}) => ({
  type: "assistant",
  isSidechain: false,
  uuid: `a${n}`,
  timestamp: ts(),
  message: { role: "assistant", stop_reason: stop, content },
  ...extra,
});
const text = (value: string) => ({ type: "text", text: value });
const toolUse = { type: "tool_use", id: "t", name: "Bash", input: { command: "ls" } };
const toolResult = [{ type: "tool_result", tool_use_id: "t", content: "ok" }];

test("Agoryx prompts are recognised by their header", () => {
  assert.ok(isAgoryxPrompt("You are Claude, in an Agoryx room — one shared conversation"));
  assert.ok(isAgoryxPrompt("You are Claude (@claude), in an Agoryx room — one shared conversation"));
  // A roster label may hold a comma; the handle after it is up to 32 characters.
  assert.ok(isAgoryxPrompt("You are Opus, the long one (@opus-with-a-long-handle-here), in an Agoryx room — one shared conversation"));
  assert.ok(isAgoryxPrompt("[agoryx · Storage · new since your last turn]\n\n── Codex · 10:00"));
  assert.ok(!isAgoryxPrompt("can you look at agoryx rooms?"));
  assert.ok(!isAgoryxPrompt("You are wrong, in my opinion"));
});

test("Claude: human exchanges are read back; Agoryx turns, tools and harness lines are not", () => {
  const dir = scratch();
  const file = join(dir, "session.jsonl");
  const agoryxTurn = [
    { type: "queue-operation", operation: "enqueue" },
    cUser("You are Claude, in an Agoryx room — one shared conversation between Ivan and Codex."),
    cAssistant([toolUse], "tool_use"),
    cUser(toolResult),
    cAssistant([text("My view: use JSONL.")], "end_turn"),
    { type: "system", subtype: "stop_hook_summary" },
  ];
  const nativeTurn = [
    cUser("Why JSONL and not SQLite? <system-reminder>internal</system-reminder>", { origin: { kind: "human" } }),
    cUser([{ type: "text", text: "Caveat: generated by local commands" }], { isMeta: true }),
    cAssistant([text("Let me check the writer.")], "tool_use"),
    cAssistant([toolUse], "tool_use"),
    cUser(toolResult),
    cAssistant([{ type: "text", text: "sidechain noise" }], "end_turn", { isSidechain: true }),
    // One API message, one line per content block, each stamped end_turn.
    cAssistant([{ type: "thinking", thinking: "" }], "end_turn", { message: { id: "msg_1", role: "assistant", stop_reason: "end_turn", content: [{ type: "thinking", thinking: "" }] } }),
    cAssistant([], "end_turn", { message: { id: "msg_1", role: "assistant", stop_reason: "end_turn", content: [text("Because appends are atomic enough"), text("and there is no native dependency.")] } }),
  ];
  const slashAndNotification = [
    cUser("<command-name>/review</command-name>\n<command-args>engine.ts</command-args>", { origin: { kind: "human" } }),
    cAssistant([text("Reviewed engine.ts: fine.")], "end_turn"),
    cUser("<task-notification>build finished</task-notification>", { origin: { kind: "task-notification" } }),
    cAssistant([text("The build finished green.")], "end_turn"),
    cUser("<local-command-stdout>ok</local-command-stdout>"),
  ];
  const interrupted = [
    cUser("Rewrite everything in Rust", { origin: { kind: "human" } }),
    cAssistant([text("Starting")], "tool_use"),
    cUser([{ type: "text", text: "[Request interrupted by user]" }]),
  ];
  writeFileSync(file, jsonl([...agoryxTurn, ...nativeTurn, ...slashAndNotification, ...interrupted]));
  try {
    const first = scanNativeSession("claude", file, 0);
    assert.deepEqual(
      first.exchanges.map((entry) => [entry.prompt, entry.reply, entry.interrupted]),
      [
        ["Why JSONL and not SQLite?", "Because appends are atomic enough\n\nand there is no native dependency.", false],
        ["/review engine.ts", "Reviewed engine.ts: fine.", false],
        [null, "The build finished green.", false],
        ["Rewrite everything in Rust", "Starting", true],
      ],
    );
    assert.equal(first.openNative, false);

    // A human turn in progress is not returned yet, and the next scan starts at it.
    const before = first.offset;
    appendFileSync(file, jsonl([cUser("And the lock file?", { origin: { kind: "human" } }), cAssistant([toolUse], "tool_use")]));
    const pending = scanNativeSession("claude", file, before, first.lastAgoryx);
    assert.deepEqual(pending.exchanges, []);
    assert.equal(pending.openNative, true);
    assert.equal(pending.offset, before);

    appendFileSync(file, jsonl([cUser(toolResult), cAssistant([text("engine.lock holds the pid.")], "end_turn")]));
    const done = scanNativeSession("claude", file, pending.offset, pending.lastAgoryx);
    assert.deepEqual(done.exchanges.map((entry) => [entry.prompt, entry.reply]), [["And the lock file?", "engine.lock holds the pid."]]);
    assert.equal(done.openNative, false);

    // An Agoryx turn in progress is not "someone typing natively".
    appendFileSync(file, jsonl([cUser("[agoryx · Storage · new since your last turn]\n\n── Codex · 10:00\nhi"), cAssistant([toolUse], "tool_use")]));
    const agoryxRunning = scanNativeSession("claude", file, done.offset, done.lastAgoryx);
    assert.deepEqual(agoryxRunning.exchanges, []);
    assert.equal(agoryxRunning.openNative, false);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

// --- Codex rollout lines ----------------------------------------------------------

const xEvent = (payload: Record<string, unknown>) => ({ timestamp: ts(), type: "event_msg", payload });
const xItem = (turn: string, item: Record<string, unknown>) => xEvent({ type: "item_completed", turn_id: turn, item });
const xTurn = (turn: string, prompt: string, answer: string | null, end: "complete" | "aborted" | null = "complete") => [
  xEvent({ type: "task_started", turn_id: turn }),
  { timestamp: ts(), type: "response_item", payload: { type: "message", role: "developer", content: [{ type: "input_text", text: "## Memory" }] } },
  { timestamp: ts(), type: "response_item", payload: { type: "message", role: "user", content: [{ type: "input_text", text: "<environment_context>cwd</environment_context>" }] } },
  xItem(turn, { type: "UserMessage", content: [{ type: "text", text: prompt }] }),
  xItem(turn, { type: "AgentMessage", phase: "commentary", content: [{ type: "Text", text: "Looking…" }] }),
  ...(answer ? [xItem(turn, { type: "AgentMessage", phase: "final_answer", content: [{ type: "Text", text: answer }] })] : []),
  ...(end === "complete" ? [xEvent({ type: "task_complete", turn_id: turn, last_agent_message: answer })] : []),
  ...(end === "aborted" ? [xEvent({ type: "turn_aborted", turn_id: turn, reason: "interrupted" })] : []),
];

test("Codex: human turns are read back without injected context; Agoryx turns are skipped", () => {
  const dir = scratch();
  const file = join(dir, "rollout.jsonl");
  writeFileSync(
    file,
    jsonl([
      { timestamp: ts(), type: "session_meta", payload: { id: "x", cwd: "/w" } },
      ...xTurn("t1", "You are Codex, in an Agoryx room — one shared conversation", "@claude P2 is up."),
      ...xTurn("t2", "Is P2 really faster?", "Yes: 3x on the bench in bench/run.txt."),
      ...xTurn("t3", "Try the other approach", "Half done", "aborted"),
      // Codex Desktop wraps the request; a turn may end without a final answer.
      xEvent({ type: "task_started", turn_id: "t3b" }),
      xItem("t3b", {
        type: "UserMessage",
        content: [
          { type: "text", text: "# Files mentioned by the user:\n\n## shot.png: /tmp/shot.png\n\n<in-app-browser-context source=\"ambient-ui-state\">\nURL: http://127.0.0.1:3000\n</in-app-browser-context>\n\n## My request:\nMake the hero less plain\n" },
          { type: "local_image", path: "/tmp/shot.png" },
        ],
      }),
      xItem("t3b", { type: "AgentMessage", phase: "commentary", content: [{ type: "Text", text: "Redrawing the hero sprite." }] }),
      xEvent({ type: "task_complete", turn_id: "t3b", last_agent_message: null }),
      // older builds: user_message / agent_message events
      xEvent({ type: "task_started", turn_id: "t4" }),
      xEvent({ type: "user_message", message: "Summarise the table" }),
      xEvent({ type: "agent_message", message: "Q1 is open; P2 leads." }),
      xEvent({ type: "task_complete", turn_id: "t4" }),
    ]),
  );
  try {
    const first = scanNativeSession("codex", file, 0);
    assert.deepEqual(
      first.exchanges.map((entry) => [entry.key, entry.prompt, entry.reply, entry.interrupted]),
      [
        ["t2", "Is P2 really faster?", "Yes: 3x on the bench in bench/run.txt.", false],
        ["t3", "Try the other approach", "Half done", true],
        ["t3b", "Make the hero less plain\n[image]", "Redrawing the hero sprite.", false],
        ["t4", "Summarise the table", "Q1 is open; P2 leads.", false],
      ],
    );
    appendFileSync(file, jsonl(xTurn("t5", "One more thing", null, null)));
    const pending = scanNativeSession("codex", file, first.offset, first.lastAgoryx);
    assert.deepEqual(pending.exchanges, []);
    assert.equal(pending.openNative, true);
    appendFileSync(file, jsonl([xEvent({ type: "task_complete", turn_id: "t5", last_agent_message: "Done." })]));
    const done = scanNativeSession("codex", file, pending.offset, pending.lastAgoryx);
    assert.deepEqual(done.exchanges.map((entry) => [entry.prompt, entry.reply]), [["One more thing", "Done."]]);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("session files are found where each CLI keeps them", () => {
  const home = scratch();
  try {
    const env = { CLAUDE_CONFIG_DIR: join(home, "claude"), CODEX_HOME: join(home, "codex") };
    const cwd = join(home, "My Work", "room.v2");
    mkdirSync(cwd, { recursive: true });
    const claudeDir = join(home, "claude", "projects", claudeProjectKey(cwd));
    mkdirSync(claudeDir, { recursive: true });
    writeFileSync(join(claudeDir, "abc.jsonl"), "");
    assert.equal(locateNativeSession("claude", "abc", cwd, env), join(claudeDir, "abc.jsonl"));
    // Found by scanning when the project dir does not match the cwd (e.g. the session moved).
    const elsewhere = join(home, "claude", "projects", "-somewhere-else");
    mkdirSync(elsewhere, { recursive: true });
    writeFileSync(join(elsewhere, "def.jsonl"), "");
    assert.equal(locateNativeSession("claude", "def", cwd, env), join(elsewhere, "def.jsonl"));
    assert.equal(locateNativeSession("claude", "nope", cwd, env), null);

    // Codex thread ids are UUIDv7; the rollout sits under the day it started.
    const ms = Date.UTC(2026, 8, 28, 12, 0, 0);
    const id = `${ms.toString(16).padStart(12, "0").replace(/^(.{8})(.{4})$/, "$1-$2")}-7000-8000-000000000001`;
    const local = new Date(ms);
    const day = join(home, "codex", "sessions", String(local.getFullYear()), String(local.getMonth() + 1).padStart(2, "0"), String(local.getDate()).padStart(2, "0"));
    mkdirSync(day, { recursive: true });
    writeFileSync(join(day, `rollout-2026-09-28T12-00-00-${id}.jsonl`), "");
    assert.equal(locateNativeSession("codex", id, cwd, env), join(day, `rollout-2026-09-28T12-00-00-${id}.jsonl`));
    const old = join(home, "codex", "sessions", "2025", "01", "02");
    mkdirSync(old, { recursive: true });
    writeFileSync(join(old, "rollout-2025-01-02T00-00-00-plain-id.jsonl"), "");
    assert.equal(locateNativeSession("codex", "plain-id", cwd, env), join(old, "rollout-2025-01-02T00-00-00-plain-id.jsonl"));
  } finally {
    rmSync(home, { recursive: true, force: true });
  }
});

// --- Engine ---------------------------------------------------------------------

const waitUntil = async (check: () => boolean, ms = 10_000) => {
  const deadline = Date.now() + ms;
  while (!check()) {
    if (Date.now() > deadline) throw new Error("condition not met in time");
    await new Promise((resolve) => setTimeout(resolve, 25));
  }
};

test("talking to Claude in its own session shows up in the room; @codex there wakes Codex, who sees it", async () => {
  const room = createTestRoom({
    rules: [{ agent: "codex", match: "check the units", reply: "@claude units look fine to me", once: true }],
  });
  try {
    room.engine.postHuman("Hello both");
    await withTimeout(room.engine.waitIdle());
    const claudeSession = room.store.state.sessions.claude!.sessionId;
    const file = locateNativeSession("claude", claudeSession, room.store.state.workspace, room.env)!;
    assert.ok(file, "the fake claude wrote its native session");
    // Agoryx's own turns are never imported back.
    assert.equal(room.store.state.messages.filter((message) => message.native).length, 0);

    const runsBefore = room.store.state.runs.length;
    appendFileSync(
      file,
      jsonl([
        cUser("Quick question just for you: is the parser safe?", { origin: { kind: "human" } }),
        cAssistant([text("Yes, it only reads complete lines.")], "end_turn"),
      ]),
    );
    await waitUntil(() => room.store.state.messages.filter((message) => message.native).length === 2);
    const quiet = room.store.state.messages.filter((message) => message.native);
    assert.deepEqual(quiet.map((message) => [message.author, message.kind, message.wakes]), [
      ["Ivan", "human", false],
      ["claude", "agent", false],
    ]);
    assert.equal(quiet[0]!.native!.agent, "claude");
    assert.equal(room.store.state.runs.length, runsBefore, "a side conversation does not start a run");

    appendFileSync(
      file,
      jsonl([
        cUser("@codex can you check the units?", { origin: { kind: "human" } }),
        cAssistant([text("Asking Codex to double-check the units.")], "end_turn"),
      ]),
    );
    await waitUntil(() => room.store.state.runs.length > runsBefore);
    await withTimeout(room.engine.waitIdle());

    const codexPrompt = room.invocations("codex").at(-1)!.prompt!;
    assert.match(codexPrompt, /Ivan \(human\) → Claude, directly in Claude's own session/);
    assert.match(codexPrompt, /check the units/);
    assert.match(codexPrompt, /Asking Codex to double-check/);
    assert.match(codexPrompt, /is the parser safe\?/, "the earlier side conversation reaches Codex too");

    // Codex addressed Claude; Claude's delta has Codex's reply but not what is already in its session.
    const claudePrompt = room.invocations("claude").at(-1)!.prompt!;
    assert.match(claudePrompt, /units look fine to me/);
    assert.doesNotMatch(claudePrompt, /check the units\?/);
    assert.doesNotMatch(claudePrompt, /is the parser safe/);
    assert.equal(room.store.state.messages.filter((message) => message.native).length, 4);
  } finally {
    await room.cleanup();
  }
});

test("while someone is mid-exchange with an agent in its own app, its room turn waits", async () => {
  const room = createTestRoom();
  try {
    room.engine.postHuman("Hello both");
    await withTimeout(room.engine.waitIdle());
    const file = locateNativeSession("codex", room.store.state.sessions.codex!.sessionId, room.store.state.workspace, room.env)!;
    appendFileSync(file, jsonl(xTurn("native-1", "Refactor the store", null, null)));
    await new Promise((resolve) => setTimeout(resolve, 150));

    const codexTurns = () => room.store.state.turns.filter((turn) => turn.agent === "codex").length;
    const before = codexTurns();
    room.engine.postHuman("Status?");
    await waitUntil(() => room.store.state.messages.some((message) => /Codex is busy in its own session/.test(message.text)));
    await waitUntil(() => room.store.state.turns.filter((turn) => turn.agent === "claude").every((turn) => turn.status !== "running"));
    assert.equal(codexTurns(), before, "codex has not been resumed under the human");
    const busy = room.store.state.messages.find((message) => /Codex is busy in its own session/.test(message.text))!;
    assert.deepEqual(busy.sys, { code: "agent.busy", agent: "Codex" });

    appendFileSync(file, jsonl([xEvent({ type: "task_complete", turn_id: "native-1", last_agent_message: "Store refactored." })]));
    await withTimeout(room.engine.waitIdle());
    assert.equal(codexTurns(), before + 1);
    const imported = room.store.state.messages.filter((message) => message.native).map((message) => message.text);
    assert.deepEqual(imported, ["Refactor the store", "Store refactored."]);
    const lastCodexPrompt = room.invocations("codex").at(-1)!.prompt!;
    assert.match(lastCodexPrompt, /Status\?/);
    assert.doesNotMatch(lastCodexPrompt, /Refactor the store/);
  } finally {
    await room.cleanup();
  }
});

test("the room shows who is busy in its own session, and when that ends", async () => {
  const room = createTestRoom();
  const seen: Array<Record<string, string>> = [];
  const unsubscribe = room.store.subscribe((event) => {
    if (event.type === "presence") seen.push(event.agents);
  });
  try {
    room.engine.postHuman("Hello both");
    await withTimeout(room.engine.waitIdle());
    assert.ok(seen.some((agents) => agents.claude === "working" && agents.codex === "working"));
    assert.deepEqual(seen.at(-1), { claude: "idle", codex: "idle" });

    const file = locateNativeSession("codex", room.store.state.sessions.codex!.sessionId, room.store.state.workspace, room.env)!;
    appendFileSync(file, jsonl(xTurn("native-1", "Refactor the store", null, null)));
    await waitUntil(() => room.engine.presence().codex === "native");
    assert.deepEqual(seen.at(-1), { claude: "idle", codex: "native" });

    appendFileSync(file, jsonl([xEvent({ type: "task_complete", turn_id: "native-1", last_agent_message: "Store refactored." })]));
    await waitUntil(() => room.engine.presence().codex === "idle");
    assert.deepEqual(seen.at(-1), { claude: "idle", codex: "idle" });
    assert.equal(seen.filter((agents) => agents.codex === "native").length, 1, "one change, one event");
  } finally {
    unsubscribe();
    await room.cleanup();
  }
});

/** Run the agent tool the way an agent's own session would: in the workspace, with no room-turn env. */
const agentTool = (room: TestRoom, args: string[], env: Record<string, string> = {}) =>
  new Promise<{ code: number; out: string; err: string }>((resolve) => {
    const base = Object.fromEntries(
      Object.entries(room.env).filter(([key]) => !/^(AGORYX_|CLAUDECODE$|CODEX_SANDBOX)/.test(key)),
    ) as Record<string, string>;
    const child = spawn(process.execPath, [agentCliScript(), "table", ...args], {
      cwd: room.store.state.workspace,
      env: { ...base, ...env },
    });
    let out = "";
    let err = "";
    child.stdout.on("data", (chunk) => (out += chunk));
    child.stderr.on("data", (chunk) => (err += chunk));
    child.on("exit", (code) => resolve({ code: code ?? 1, out, err }));
  });

test("agents write to the table from their own sessions; the room signs, shows and relays those moves", async () => {
  const room = createTestRoom();
  try {
    room.engine.postHuman("Hello both");
    await withTimeout(room.engine.waitIdle());
    assert.match(room.invocations("claude")[0]!.prompt!, /Outside a room turn[^\n]*table … --as claude/);
    const runsBefore = room.store.state.runs.length;

    // Claude, in Claude Code: its shell says who it is.
    const proposed = await agentTool(room, ["propose", "Store kelvin", "--body", "no negative values"], { CLAUDECODE: "1" });
    assert.equal(proposed.code, 0, proposed.err);
    assert.match(proposed.out, /^P1 · /);
    const option = room.store.state.table.options[0]!;
    assert.equal(option.by, "claude");
    assert.equal(room.store.state.runs.length, runsBefore, "a table move from a native session starts no run");

    // Nobody is working and nothing says who wrote it: the room refuses to guess.
    const unsigned = await agentTool(room, ["ask", "Which unit in the UI?"]);
    assert.equal(unsigned.code, 1);
    assert.match(unsigned.err, /--as claude or --as codex/);

    // Explicit signature.
    const asked = await agentTool(room, ["ask", "Which unit in the UI?", "--as", "codex"]);
    assert.equal(asked.code, 0, asked.err);
    assert.equal(room.store.state.table.questions[0]!.by, "codex");

    // Unsigned, while someone is mid-exchange with Codex in its own app: that is Codex.
    const codexFile = locateNativeSession("codex", room.store.state.sessions.codex!.sessionId, room.store.state.workspace, room.env)!;
    appendFileSync(codexFile, jsonl(xTurn("native-t", "What do you think of P1?", null, null)));
    const supported = await agentTool(room, ["support", "P1", "kelvin keeps the math simple"]);
    assert.equal(supported.code, 0, supported.err);
    assert.equal(room.store.state.table.notes.at(-1)!.by, "codex");
    appendFileSync(codexFile, jsonl([xEvent({ type: "task_complete", turn_id: "native-t", last_agent_message: "Supported P1." })]));
    await waitUntil(() => room.store.state.messages.some((message) => message.text === "Supported P1."));

    room.engine.postHuman("Where are we?");
    await withTimeout(room.engine.waitIdle());
    const claudePrompt = room.invocations("claude").at(-1)!.prompt!;
    const codexPrompt = room.invocations("codex").at(-1)!.prompt!;
    assert.match(claudePrompt, /Codex \(in its own session, outside the room\) on the table: .*P1/);
    assert.doesNotMatch(claudePrompt, /Claude \(in its own session, outside the room\) on the table/, "its own moves are not echoed back");
    assert.match(codexPrompt, /Claude \(in its own session, outside the room\) on the table: .*Store kelvin/);
    assert.doesNotMatch(codexPrompt, /Codex \(in its own session/);
    // Chronological: Claude's proposal comes before the human's question.
    assert.ok(codexPrompt.indexOf("Store kelvin") < codexPrompt.indexOf("Where are we?"));
  } finally {
    await room.cleanup();
  }
});

test("an edit to the canonical file made in an agent's own session is credited to that agent", async () => {
  const room = createTestRoom({ settings: { doc: "README.md" } });
  try {
    const readme = join(room.store.state.workspace, "README.md");
    writeFileSync(readme, "# Units\n");
    room.engine.postHuman("Hello both");
    await withTimeout(room.engine.waitIdle());
    await waitUntil(() => room.store.state.docRevisions.length === 1);
    assert.equal(room.store.state.docRevisions[0]!.by, "Ivan", "a file that appears between turns, with no one in their own session, is the human's");

    const file = locateNativeSession("codex", room.store.state.sessions.codex!.sessionId, room.store.state.workspace, room.env)!;
    appendFileSync(file, jsonl(xTurn("native-doc", "Write down the unit decision", null, null)));
    await waitUntil(() => room.engine.presence().codex === "native");
    writeFileSync(readme, "# Units\n\nStore kelvin; convert at the edges.\n");
    await waitUntil(() => room.store.state.docRevisions.length === 2);
    const revision = room.store.state.docRevisions[1]!;
    assert.deepEqual([revision.by, revision.native, revision.turnId], ["codex", true, undefined]);
    appendFileSync(file, jsonl([xEvent({ type: "task_complete", turn_id: "native-doc", last_agent_message: "Wrote it down." })]));

    room.engine.postHuman("@claude does the README match what we agreed?");
    await withTimeout(room.engine.waitIdle());
    const prompt = room.invocations("claude").at(-1)!.prompt!;
    assert.match(prompt, /README\.md \(the room's canonical file\) changed since your last turn — Codex \(in its own session\) \+2 −0/);
    assert.match(prompt, /\+ Store kelvin; convert at the edges\./);
  } finally {
    await room.cleanup();
  }
});
